### PR TITLE
gpu_fdinfo bug fixes, almost full support for Intel is finally here

### LINKED ISSUE #1082: MangoHud Intel GPU metrics
This issue is for tracking the progress and issues with Intel GPU metrics. dGPU and iGPU.

### Current state
- `intel_gpu_top` has to be installed and it has to be setcap'd  e.g `sudo setcap cap_perfmon=+ep /usr/bin/intel_gpu_top`
- We are set up to get GPU load at least from `intel_gpu_top`
- MangoHud is only able to run `intel_gpu_top` unhindered outside of proton/runtime
- In order for us to run `intel_gpu_top` you need to have flatpak installed and set sniper runtime to beta

### LINKED ISSUE #1454: Playing Need for speed most wanted 2005 (32 bit) does not display GPU usage. It is always at 0%.
**Describe the bug**
When playing nfs mw, frame rate works but GPU usage is always at 0%. I use mangohud with bottes and downloaded mangohud from the gnome store. No other games to test unfortunately. `flatpak override --filesystem=xdg-config/MangoHud:ro` command was applied. 

**List relevant hardware/software information**
- Fedora Silverblue 40/Project Bluefin stable branch
- MangoHud flathub 0.7.2
- Intel Arc Graphics that comes with intel core ultra 7 155h laptop SoC 

**To Reproduce**
1. Ensure "Monitor Performance" in bottles is toggled
2. Run NFSMW 2005 executable (speed.exe) 
3. Overlay will show GPU usage as 0%

**Expected behavior**
GPU usage needs to be displayed accurately.

**Screenshots**
Screenshot from 2024-10-05 15-51-55

### PR DESCRIPTION
**Pull request by 17314642**
Resolves #1082
Resolves #1454

First I would like to thank you these guys for testing patches: @PerAstraAdDeum, @nokia8801 and @retrixe for helping in development.

In short, this pr fixes: 

1. wrong power usage for some people (https://github.com/flightlessmango/MangoHud/issues/1082#issuecomment-2513772813)
2. wrong gpu usage in some cases
3. vram support for integrated gpus in xe (forgot about those :crying_cat_face:)
4. 1 million watt gpu power at start (which confused one user when testing)
5. some info messages.
6. gpu clock support for i915 and xe
7. fan speed support (tested only on i915 and xe, should have linux 6.12+)
8. generic hwmon support (tested only on i915 and xe)
9. throttling support (only i915 and xe)
10. temperature support (only i915, should have linux 6.13+)
11. shows all gpus by default, otherwise user can choose which gpus he wants to see by using `pci_dev` or `gpu_list`

To summarize: pretty much every vital metric is available now for intel.

struct gpu_metrics:
  - [x] int load;
  - [X] int temp; (**only i915, no xe support by intel yet**)
  - [ ] int junction_temp {-1}; (**isn't exposed by intel**)
  - [ ] int memory_temp {-1}; (**isn't exposed by intel**)
  - [X] float memoryUsed;
  - [ ] float memoryTotal; (**isn't exposed by intel**)
  - [ ] int MemClock; (**isn't exposed by intel**)
  - [X] int CoreClock;
  - [X] float powerUsage;
  - [ ] float apu_cpu_power;
  - [ ] int apu_cpu_temp;
  - [X] bool is_power_throttled;
  - [X] bool is_current_throttled;
  - [X] bool is_temp_throttled;
  - [X] bool is_other_throttled;
  - [ ] float gtt_used; (**not used by mangohud**)
  - [X] int fan_speed; (**only i915, no xe support by intel yet**)
  - [X] int voltage;
  
  
Example metrics (using linux kernel 6.13): 
image

### CODE REVIEW

File: src/gpu_fdinfo.h [hunk 1]
```diff
@@ -67,16 +67,28 @@ class GPU_fdinfo {
         : module(module)
         , pci_dev(pci_dev)
     {
-        SPDLOG_DEBUG("GPU driver is \"{}\"", module);
+        SPDLOG_INFO("GPU driver is \"{}\"", module);
```
Comment (flightlessmango) [inline src/gpu_fdinfo.h:112]: We don't want to print things every time unless it's not expected, this should be debug

File: src/gpu_fdinfo.h [hunk 2]
```diff
@@ -67,16 +67,28 @@ class GPU_fdinfo {
...
             drm_memory_type = "drm-total-local0";
         } else if (module == "xe") {
             drm_engine_type = "drm-total-cycles-rcs";
             drm_memory_type = "drm-resident-vram0";
+
+            if (
+                fdinfo_data.size() > 0 &&
+                fdinfo_data[0].find(drm_memory_type) == fdinfo_data[0].end()
+            ) {
+                SPDLOG_INFO(
```
Comment (flightlessmango) [inline src/gpu_fdinfo.h:128]: Should also be debug

File: src/gpu.cpp [hunk 3]
```diff
@@ -66,7 +66,7 @@ GPUS::GPUS(overlay_params* params) : params(params) {
         std::shared_ptr<GPU> ptr = std::make_shared<GPU>(node_name, vendor_id, device_id, pci_dev);
         available_gpus.emplace_back(ptr);
 
-        SPDLOG_DEBUG("GPU Found: node_name: {}, vendor_id: {:x} device_id: {:x} pci_dev: {}", node_name, vendor_id, device_id, pci_dev);
```
Comment (flightlessmango) [inline src/gpu.cpp:69]: should be debug

File: src/gpu.cpp [hunk 4]
```diff
@@ -66,7 +66,7 @@ GPUS::GPUS(overlay_params* params) : params(params) {
...
+        SPDLOG_INFO("GPU Found: node_name: {}, vendor_id: {:x} device_id: {:x} pci_dev: {}", node_name, vendor_id, device_id, pci_dev);
```
Comment (flightlessmango) [inline src/gpu.cpp:80]: should be debug

File: src/gpu_fdinfo.h (hunk 1 above)
Comment (17314642) [reply src/gpu_fdinfo.h:112]: Gpu driver is also printen only once

File: src/gpu.cpp [hunk 5]
```diff
@@ -153,7 +153,7 @@ void GPUS::find_active_gpu() {
                 for (const auto& gpu : available_gpus) {
                     if (gpu->pci_dev == drm_pdev) {
                         gpu->is_active = true;
-                        SPDLOG_DEBUG("Active GPU Found: node_name: {}, pci_dev: {}", gpu->name, gpu->pci_dev);
```
Comment (flightlessmango) [inline src/gpu.cpp:156]: should be debug

File: src/gpu.cpp [hunk 6]
```diff
@@ -173,7 +173,7 @@ void GPUS::find_active_gpu() {
                 for (auto& pid : gpu->nvidia_pids()) {
                     if (pid == getpid()) {
                         gpu->is_active = true;
-                        SPDLOG_DEBUG("Active GPU Found: node_name: {}, pci_dev: {}", gpu->name, gpu->pci_dev);
```
Comment (flightlessmango) [inline src/gpu.cpp:176]: should be debug

File: src/gpu_fdinfo.h (hunk 2 above)
Comment (17314642) [reply src/gpu_fdinfo.h:128]: Same thing

File: src/gpu.cpp (hunk 3 above)
Comment (17314642) [reply src/gpu.cpp:69]: Shouldn't user be able to see this easier? Considering these things get printed once per launch. Instead of asking him to change his SPDLOG_LEVEL.

File: src/hud_elements.cpp [hunk 7]
```diff
@@ -250,22 +250,20 @@ void HudElements::gpu_stats(){
                 ImGui::PopFont();
             }
 
-            if (HUDElements.vendorID == 0x1002 || HUDElements.vendorID == 0x10de){
-                if (HUDElements.params->enabled[OVERLAY_PARAM_ENABLED_gpu_fan] && cpuStats.cpu_type != "APU"){
-                    ImguiNextColumnOrNewRow();
-                    right_aligned_text(text_color, HUDElements.ralign_width, "%i", gpu->metrics.fan_speed);
+            if (HUDElements.params->enabled[OVERLAY_PARAM_ENABLED_gpu_fan] && cpuStats.cpu_type != "APU"){
```
Comment (flightlessmango) [inline src/hud_elements.cpp:253]: `cpuStats.cpu_type` should be deprecated in favor of `gpu->is_apu()`.
Only AMD is being set as APU atm so intel needs to be hooked up there

Comment (17314642) [reply src/hud_elements.cpp:253]: cpu_type is completetly unused, even for amd

Comment (17314642) [reply src/hud_elements.cpp:253]: and do you mean it needs changing from `cpuStats.cpu_type != "APU"` to `!gpu->is_apu()`?

File: src/gpu.cpp (hunk 3 above)
Comment (flightlessmango) [reply src/gpu.cpp:69]: The problem is that it's usually not once per launch, mangohud attaches to many random processes and spams the logs.
Unless something is out of the ordinary or something is wrong is when we want to print

File: src/gpu.cpp (hunk 6 above)
Comment (17314642) [reply src/gpu.cpp:176]: since find_active_gpu is nuked, i dont think this is necessary

Comment (flightlessmango) [reply src/gpu.cpp:176]: You're right :+1:

File: src/hud_elements.cpp (hunk 7 above)
Comment (17314642) [reply src/hud_elements.cpp]: done, i think?

Comment (17314642) [reply src/hud_elements.cpp]: and I don't know currently how to detect if gpu is an integrated one, so that will have to wait

Comment (flightlessmango) [reply src/hud_elements.cpp]: Yes it should be changed to `!gpu->is_apu()`

Comment (17314642) [reply src/hud_elements.cpp]: I changed it already

File: src/gpu_fdinfo.h (hunk 1 above)
Comment (flightlessmango) [reply src/gpu_fdinfo.h]: As mentioned earlier, the problem is that nothing is mentioned once when launched from steam etc, it will spam the logs

File: src/gpu.cpp (hunk 3 above)
Comment (flightlessmango) [reply src/gpu.cpp:69]: Oh it's been changed already, I'm learning I don't understand how this tool works.

Comment (17314642) [reply src/gpu.cpp:69]: yeah, it's not really intuitive, i already force pushed all the changes
